//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoForce.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER09;Initial Catalog=PhotoSorter3Mvvm;Persist Security Info=Tr" +
            "ue;User ID=sa")]
        public string PhotoSorter3MvvmConnectionString {
            get {
                return ((string)(this["PhotoSorter3MvvmConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER09;Initial Catalog=PhotoSorter3Mvvm;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=pass@word1")]
        public string PhotoSorter3MvvmConnectionString1 {
            get {
                return ((string)(this["PhotoSorter3MvvmConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER09;Initial Catalog=PhotoSorter4;Persist Security Info=True;U" +
            "ser ID=sa")]
        public string PhotoSorter4ConnectionString {
            get {
                return ((string)(this["PhotoSorter4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER09;Initial Catalog=FreedPhotoSorter3;Persist Security Info=T" +
            "rue;User ID=sa")]
        public string FreedPhotoSorter3ToMVVMConnectionString {
            get {
                return ((string)(this["FreedPhotoSorter3ToMVVMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER09;Initial Catalog=FreedPhotoSorter3;User ID=sa")]
        public string FreedPhotoSorter3ConnectionString {
            get {
                return ((string)(this["FreedPhotoSorter3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=FreedPhotoSorter3;Persist Security Info=T" +
            "rue;User ID=sa")]
        public string FreedPhotoSorter3ConnectionString1 {
            get {
                return ((string)(this["FreedPhotoSorter3ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=photosorter;Persist Security Info=True;Us" +
            "er ID=sa")]
        public string photosorterConnectionString {
            get {
                return ((string)(this["photosorterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=PhotoForce4;User ID=sa")]
        public string PhotoForce4ConnectionString {
            get {
                return ((string)(this["PhotoForce4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=PhotoForce4;Persist Security Info=True;Us" +
            "er ID=sa")]
        public string PhotoForce4ConnectionString1 {
            get {
                return ((string)(this["PhotoForce4ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=PhotoForce4;Persist Security Info=True;Us" +
            "er ID=sa;Password=pass@word1")]
        public string PhotoForce4ConnectionString2 {
            get {
                return ((string)(this["PhotoForce4ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=PF@MTC;User ID=sa")]
        public string PF_MTCConnectionString {
            get {
                return ((string)(this["PF_MTCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=PF@MTC;User ID=sa;Password=pass@word1")]
        public string PF_MTCConnectionString1 {
            get {
                return ((string)(this["PF_MTCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=PhotoForce4;Integrated Security=True")]
        public string PhotoForce4ConnectionString3 {
            get {
                return ((string)(this["PhotoForce4ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=developer40;Initial Catalog=PF@MTC;User ID=sa;Password=pass@word1")]
        public string PF_MTCConnectionString2 {
            get {
                return ((string)(this["PF_MTCConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEVELOPER40;Initial Catalog=PhotoForce4;User ID=sa;Password=pass@word" +
            "1")]
        public string PhotoForce4ConnectionString4 {
            get {
                return ((string)(this["PhotoForce4ConnectionString4"]));
            }
        }
    }
}
